version: 0.2

phases:
  install:
    commands:
      - npm install -g typescript
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the dist folder
      - npm run format
      - npm run test
      - npm run test:e2e
      - npm run build
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - dist/**/*
    - package.json
    - package-lock.json
    - node_modules/**/*
